/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#005e9f',
        secondary: '#45681c',
        tertiary: '#735c00',
        ivory: '#fcf9f1',
        paper: '#ffffff',
        taupe: '#e5e2da',
        beige: '#f1eee6',
        charcoal: '#1c1c17',
        obsidian: '#31312b',
        'dark-surface': '#00497e',
        'muted-dark': '#404751',
        'muted-light': '#f3f1e9',
        peach: '#ffe085',
        coral: '#0077c8',
        rose: '#005e9f',
        blush: '#f6f3eb',
        mint: '#c3ed91',
        leaf: '#486b1f',
        'mint-strong': '#aad37a',
        'border-light': '#c0c7d3',
        'border-dark': 'rgba(0, 94, 159, 0.18)',
        lavender: '#d2e4ff',
        'lavender-dim': '#9fcaff',
        'aegean-blue': '#0077C8',
        'olive-green': '#486B1F',
        'sunflower-yellow': '#F2C400',
        'santorini-white': '#F7F4EC',
        'glass-surface': 'rgba(247, 244, 236, 0.6)',
        'glass-border': 'rgba(255, 255, 255, 0.4)',
      },
      fontFamily: {
        sans: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['EB Garamond', 'Cormorant Garamond', 'Georgia', 'serif'],
        label: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      spacing: {
        sidebar: '256px',
        'section-gap': '5rem',
      },
    },
  },
  plugins: [],
};
